<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\DgDevelopment.Identity.Application\DgDevelopment.Identity.Application.csproj" />
    <ProjectReference Include="..\DgDevelopment.Identity.Infrastructure\DgDevelopment.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\DgDevelopment.Identity.OAuth\DgDevelopment.Identity.OAuth.csproj" />
    <ProjectReference Include="..\DgDevelopment.Identity.Saml\DgDevelopment.Identity.Saml.csproj" />
    <ProjectReference Include="..\DgDevelopment.Identity.ServiceDefaults\DgDevelopment.Identity.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.18" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
